import React, { useEffect, useState } from "react";
import Head from "next/head";
import Layout from "../components/Layout";
import SearchBar from "../components/SearchBar/SearchBar";
import Coins from "../components/Coins/Coins";

export default function Home({}) {
  const [search, setSearch] = useState("");
  const [data, setData] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch("/api/fetchData");
        const data = await res.json();
        setData(data);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []); // Runs only once on component mount

  const filteredAllCoins = data.filter((coin) =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );

  const handleChange = (e) => {
    setSearch(e.target.value.toLowerCase());
  };

  return (
    <Layout>
      <div>
        <Head>
          <title>Next | Crypto Currency</title>
          <meta name="description" content="Generated by Serhii" />
        </Head>

        <SearchBar
          value={search}
          type="text"
          placeholder="search"
          onChange={handleChange}
        />
        <Coins data={filteredAllCoins} />
      </div>
    </Layout>
  );
}
